### ISSUE TITLE
Establish local workflow for working with ParcelQuest data

### ISSUE THREAD

**Issue by ian-r-rose** [cagov/data-infrastructure#221] opened 2023-10-12 17:46 UTC
ParcelQuest data is private, so we can't share any derived data products via our S3 bucket. Instead, we are generating some local utility functions that allow us to do the following:

1. Take our public building footprints datasets hosted in S3 and do a spatial join on any subset of parcel shapes
2. Write some heuristics for footprints which intersect more than one parcel (specific numbers are made up, we should make it tune-able and set good defaults in collaboration with @fennisreed):
    1. If a footprint is ~90% in a parcel, just assign it to that parcel, drop any others that might intersect with it.
    2. If a footprint has ~30-70% intersections with a parcel, split the footprint and assign the sub-footprints to the relevant parcels.

The resulting footprints-with-parcels dataset should be able to easily generate the following "final" data files:

1. A table with Parcel Index and building footprint area (i.e., the corrected area of the footprint as processed above)
2. A spatial file (shapefile, parquet, or otherwise) with Parcels as primary geometry, footprint area, and the geometry of all footprints that might exist on the parcel aggregated/ST_UNION'd.

**Comment by britt-allen** [comment] 2023-10-16 17:04
This is a duplicate of #153, copying data from this to there and closing.

**Closed by britt-allen** 2023-10-16 17:04 UTC
